### ISSUE TITLE
Add address book feature

### ISSUE THREAD

**Issue by dogemos** [everett-protocol/keplr-extension#6]
Due to restrictions in the browser extensions, the page that the user was previously in resets (and all the input values gone) when the wallet is closed and reopened.

In most scenarios, this isn't a problem. However, as some exchanges require users to copy and paste the address **and** the memo this introduces some UX challenges when transferring from Keplr to an exchange.

Having an address book of address + memo will partially solve this issue.

**Comment by Thunnini** [comment]
We finished publish the version v0.5.0 that includes korean language support and the permission system for external website. I believe that address book feature can be included in v0.5.1 in the near future.

**Comment by Thunnini** [comment]
The initial implementation is merged at 2bf569c

**Comment by Thunnini** [comment]
This was implemented in v0.5.3. And it is released on firefox, and it will be released on chrome in 2~3 days.
